version: "3"

services:
  web-srv:
    image: leopays/web-srv:stub
    environment:
      NODE_ENV: production
      PORT: 80
      DATA_DIR: /data
      #ACME_CHALLENGE: "*.*"
    env_file: .env
    volumes:
      #- "../data/srv/acme-challenge:/srv/public/.well-known/acme-challenge"
      - "../../../data/web-srv:/data"
    ports:
      - "80:80"
      - "443:443"
