version: "3"

services:
  srv:
    image: leopays/srv:stub
    environment:
      NODE_ENV: production
      PORT: 80
      DATA_DIR: /data
      DB_HOST: mongodb
      #ACME_CHALLENGE: "*.*"
    env_file: .env
    volumes:
      #- "../data/srv/acme-challenge:/srv/public/.well-known/acme-challenge"
      - "../data/srv:/data"
    ports:
      - "80:80"
      - "443:443"
