version: "3"

services:
  web-srv:
    image: leopays/web-srv:latest
    environment:
      NODE_ENV: production
      PORT: 80
      DATA_DIR: /data
      DB_HOST: mongodb
      #ACME_CHALLENGE: "*.*"
    env_file: .env
    volumes:
      #- "../data/web-srv/acme-challenge:/web-srv/public/.well-known/acme-challenge"
      - "../data/web-srv:/data"
    ports:
      - 80:80
      - 443:443
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "../data/mongodb:/data"
